server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
      - id: payment_routh
        uri: lb://cloud-payment-service
        predicates:
          - Path=/payment/get/**

      - id: payment_routh2
        uri: lb://cloud-payment-service
        predicates:
          - Path=/payment/lb/**
      discovery:
        locator:
          enabled: true
eureka:
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    hostname: cloud-gateway-service

